#Input Files (specify path to receptor and ligand files)
receptor: "data/1stp_receptor.pdb"
ligand: "data/biotin.pdb"


#Docking box parameters

autobox_ref: "data/biotin.pdb" #Molecule to center box on
autobox_buffer: 8              #Add 8 A as buffer around ligand

#Manual box parameters, to enable remove comments and commeent out autobox_ref
#Must modify snakefile as well
# center:
#   x: 26.3
#   y: 12.6
#   z: 18.6
# size:
#   x: 16
#   y: 16
#   z: 16

#Smina search paramaters
cpu_cores: 4
exhaustiveness: 8
num_modes: 100

#Output
output_name: "results/docked_biotin_streptavidin.pdbqt" #Docked ligand result
clean_csv: "results/clean_scores.csv" #Smina.log to clean csv file
smina_plot: "results/smina_plot.png" #plotting RMSD vs Affinity
smina_log: "results/smina.log" #Log results

