name: smina_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - atk-1.0=2.38.0=h4bec284_2
  - attrs=25.4.0=pyh71513ae_0
  - blosc=1.21.5=hafa3907_1
  - brotli-python=1.2.0=py311h55b82c4_0
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.18.0=h99e66fa_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311h137bacd_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh707e725_0
  - coin-or-cbc=2.10.12=h26cd4a2_1
  - coin-or-cgl=0.60.7=ha3c4b8c_0
  - coin-or-clp=1.17.8=hf0ee74e_0
  - coin-or-osi=0.108.10=h13a241d_0
  - coin-or-utils=2.11.11=h86ddba1_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7.1=pyhe01879c_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.3.1=py311h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=hd1e62a0_3
  - docutils=0.22.3=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_1
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.55.3=py311h46256e1_0
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.16=h8616949_0
  - gdk-pixbuf=2.42.10=h688160f_2
  - gettext=0.21.0=h4e8c18a_2
  - giflib=5.2.2=h10d778d_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glew=2.1.0=h046ec9c_2
  - glib=2.80.2=h0f68cf7_0
  - glib-tools=2.80.2=hc27840c_0
  - glm=1.0.1=h2ef5d4a_0
  - graphite2=1.3.14=h21dd04a_2
  - graphviz=9.0.0=hee74176_1
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - gtk2=2.24.33=h7c1209e_2
  - gts=0.7.6=h53e17e3_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=9.0.0=h053f038_0
  - hdf4=4.2.15=h7aa5921_5
  - hdf5=1.14.3=nompi_h687a608_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.11=pyhd8ed1ab_0
  - immutables=0.21=py311h13e5629_2
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h46256e1_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.8=py311h6d0c2b6_0
  - krb5=1.20.1=h428f121_1
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libaec=1.1.4=ha6bc127_0
  - libblas=3.11.0=1_he492b99_openblas
  - libboost=1.82.0=h99d8d82_6
  - libcblas=3.11.0=1_h9b27e0a_openblas
  - libclang=14.0.6=default_h182e8cd_2
  - libclang-cpp15=15.0.7=default_h7151d67_5
  - libclang13=14.0.6=default_h9f4243d_2
  - libcurl=8.9.1=h3a17b82_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=h04015c4_1
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.4=hecd8cb5_1
  - libgd=2.3.3=hfbc75c6_4
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libglib=2.80.2=h0f68cf7_0
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libintl-devel=0.25.1=h3184127_1
  - libjpeg-turbo=2.0.0=hca72f7f_0
  - libkrb5=1.21.3=h54be378_4
  - liblapack=3.11.0=1_h859234e_openblas
  - liblapacke=3.11.0=1_h94b3770_openblas
  - libllvm14=14.0.6=h26321d7_4
  - libllvm15=15.0.7=hbedff68_4
  - libllvm18=18.1.7=hd5e122f_0
  - libnetcdf=4.9.2=nompi_h7334405_114
  - libnghttp2=1.58.0=h64cf6d3_1
  - libogg=1.3.5=he3325bb_1
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopus=1.5.2=he3325bb_0
  - libpng=1.6.43=h92b6c6a_0
  - libpq=17.4=h40f65ae_2
  - libprotobuf=5.29.3=h66a43dd_1
  - librsvg=2.58.0=h7b06fc5_1
  - libsodium=1.0.18=h1de35cc_0
  - libsqlite=3.46.0=h1b8f9f3_0
  - libssh2=1.11.0=hd019ec5_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libvorbis=1.3.7=ha059160_2
  - libwebp=1.3.2=hc927772_1
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - libzip=1.10.1=hc158999_3
  - libzlib=1.2.13=h87427d6_6
  - llvm-openmp=19.1.7=ha54dae1_1
  - lmdb=0.9.31=hc8b0dd6_0
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib=3.10.0=py311hecd8cb5_0
  - matplotlib-base=3.10.0=py311h919b35b_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mysql=8.4.0=h5364baf_2
  - mysql-common=8.3.0=hfd7a639_4
  - mysql-libs=8.3.0=ha9146f8_4
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h923df54_0
  - nspr=4.38=hee0b3f1_0
  - nss=3.100=h6606ded_0
  - numpy=2.3.5=py311hf157cb9_0
  - openbabel=3.1.1=py311he4d38a6_9
  - openjpeg=2.5.2=h2d09ccc_1
  - openldap=2.6.10=h5897940_0
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hca9a5ca_1
  - pango=1.50.14=h19c1c8a_2
  - pcre2=10.43=h0ad2156_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.8=pyhd8ed1ab_0
  - pillow=11.1.0=py311h935ef2f_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=ha059160_1
  - plac=1.4.5=pyhd8ed1ab_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - pmw=2.1.1=py311h6eed73b_0
  - psutil=7.1.3=py311h62e9434_0
  - pulp=2.8.0=py311h6dafe98_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py311hd2a4513_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymol-open-source=3.0.0=py311h9d95b75_8
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.10=py311h6d0c2b6_1
  - pyqt5-sip=12.13.0=py311h46256e1_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.1=pyhcf101f3_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311he13f9b5_0
  - qt-main=5.15.2=hf83fbd5_12
  - readline=8.3=h49f2429_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.29.0=py311hd2a4513_0
  - seaborn=0.13.2=py311hecd8cb5_3
  - setuptools=78.1.1=py311hecd8cb5_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - sip=6.7.12=py311hd39e593_0
  - six=1.17.0=pyhe01879c_1
  - slack-sdk=3.39.0=pyhd8ed1ab_0
  - slack_sdk=3.39.0=hd8ed1ab_0
  - smart_open=7.5.0=pyhcf101f3_0
  - smina=2020.12.10=h240833e_2
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=9.13.7=hdfd78af_0
  - snakemake-interface-common=1.22.0=pyhd4c3c12_0
  - snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
  - snakemake-interface-logger-plugins=2.0.0=pyhd4c3c12_0
  - snakemake-interface-report-plugins=1.3.0=pyhd4c3c12_0
  - snakemake-interface-scheduler-plugins=2.0.2=pyhd4c3c12_0
  - snakemake-interface-storage-plugins=4.2.3=pyhd4c3c12_0
  - snakemake-minimal=9.13.7=pyhdfd78af_0
  - snappy=1.2.2=h01f5ddf_1
  - sqlite=3.50.2=hc8b0dd6_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.15=h3a5a201_0
  - toml=0.10.2=pyhd8ed1ab_2
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.1=py311h46256e1_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py311h46256e1_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.45.1=py311hecd8cb5_0
  - wrapt=1.17.3=py311h13e5629_1
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=h4132b18_3
  - yte=1.8.1=pyha770c72_0
  - zlib=1.2.13=h87427d6_6
  - zstandard=0.23.0=py311h13e5629_3
  - zstd=1.5.6=h915ae27_0
prefix: /Users/alex/miniconda3/envs/smina_env
